### ISSUE TITLE
Work out the kinks in mockBackend for demo.spec.ts

### ISSUE THREAD

**Issue by jpdonaghy** [jpdonaghy/angular-dynamic-forms#10]
I introduced http to the demo to load meta data and that killed the unit because of an un-handled http response.  I looked for a good example of mockBackend and found a few but nothing worked after pounding away on it for 5 minutes!

**Comment by thelgevold** [comment]
I will take a look at this. We should wrap the http call in a service instead of hitting the http service directly from the component. I can make a meta service to wrap this. This will simplify the testing of both the service and the component,

**Comment by thelgevold** [comment]
I have moved the call to a service and mocked at the service level instead. We can mock http calls in cases where we have to, but I find this to be easier since there are fewer dependencies to setup.

**Comment by jpdonaghy** [comment]
:+1:
