### ISSUE TITLE
Create a dropdown element on the page

### ISSUE THREAD

**Issue by thelgevold** [jpdonaghy/angular-dynamic-forms#12]
We should wire up a dropdown to our form. 
I will create an initial version that doesn't need a second codelist request to get the data

**Comment by jpdonaghy** [comment]
Let's us the codeList model...

**Comment by thelgevold** [comment]
Ok. I can bring in a code list on demand based on some event in our form

**Comment by thelgevold** [comment]
I wil surface select-meta.json

**Comment by jpdonaghy** [comment]
I pushed models/code-list.ts which has an interface for the CodeList and CodeListItem.

**Comment by thelgevold** [comment]
ok, cool

**Comment by thelgevold** [comment]
Do we need to surface both longName and shortName? If we only need one of them it would be good to resolve to just a generic 'name' property in the model, once it leaves the parser.

**Comment by jpdonaghy** [comment]
We have instances where we need to show shortName - longName in the dropdown when longName is being used as a description. i.e. 'Ambidextrous - Able to use each hand equally well'

**Comment by jpdonaghy** [comment]
I'll change the interface to have label and optional description property.  The parsers can reconcile shortName/longName.

**Comment by jpdonaghy** [comment]
Pushed
