### ISSUE TITLE
Add codelist support to parser

### ISSUE THREAD

**Issue by jpdonaghy** [jpdonaghy/angular-dynamic-forms#13]
Parser should handle codeList objects both embedded and external href.

**Comment by thelgevold** [comment]
I have added support for external code lists. just doing some cleanup and fixing tests now.

**Comment by jpdonaghy** [comment]
Does it support dynamic href and query?  Those both need to be inputs that are watched.

**Comment by thelgevold** [comment]
Not at the moment. We have to take a look at that in general. I see that as being part of a bigger question dependency discussion.

**Comment by jpdonaghy** [comment]
The codeList service will at a minimum need to have these dynamic inputs and refetch it's data.  The dependencies will be handled by a higher controller, which will require some thought.

**Comment by jpdonaghy** [comment]
We'll need to add external reference information to the CodeList interface.

**Comment by thelgevold** [comment]
Yes. I just pushed. This is nowhere near a final solution, but just a way to add a code list question with a url to the meta. It will then pull in the data based on that url and render it in the form. Have to fix two unit tests that broke.

**Comment by thelgevold** [comment]
It only pulls it in once on initial load, so loading on demand has to be revisited

**Comment by jpdonaghy** [comment]
We'll add a watch on the href and querystring inputs and then hit http again.

**Comment by jpdonaghy** [comment]
I'll update the sample meta to reflect the actual codeList data structure.  And update the parser.

**Comment by thelgevold** [comment]
ok, cool

**Comment by jpdonaghy** [comment]
Just pushed some changes, take a look.  Fixed up the sample meta to reflect the specification.

**Comment by jpdonaghy** [comment]
I'm going to add support for embedded codeLists.

**Comment by jpdonaghy** [comment]
We'll need a separate CodeListService that has an Observable of the listItems, it will expose the href/query for the dependency controller.  The MetaService, which each form should have an instance of, will not handle the http directly.

**Comment by jpdonaghy** [comment]
Is there a reason for these 'services' to just be plain Angular and not just plain TS?

**Comment by thelgevold** [comment]
I think we can separate out the code list call to its own method that returns an observable. We can then call it on demand later and as part of the initial load. Does that make sense. I think meta service should be plain TS. Right now it only relies on angular for DI. Most of it is just rxjs

**Comment by jpdonaghy** [comment]
The Angular form component will need an injectable service, we can have a wrapper for this and any heavy lifting is just TS imported by the wrapper.

**Comment by jpdonaghy** [comment]
Pushed changes to the parser to support synchronous codeLists, meaning the listItems come with the meta-data and not asynchronously through href->http.
