### ISSUE TITLE
Fix console error when running ng server

### ISSUE THREAD

**Issue by jpdonaghy** [jpdonaghy/angular-dynamic-forms#14]
Uncaught (in promise) TypeError: object is not a constructor
    at then (native)

**Comment by thelgevold** [comment]
This is related to a version issue with es6-shim. I just took us to beta 9, but it's not fixed there. Hopefully it will be fixed in beta 10.
We need es6-shim 0.35.0, but it currently doesn't work with beta.

**Comment by thelgevold** [comment]
Fixed with Beta 11 upgrade
