### ISSUE TITLE
What implementations of ViewModelBase do we need?

### ISSUE THREAD

**Issue by jpdonaghy** [jpdonaghy/angular-dynamic-forms#3]
We have TextboxViewModel.  What else do we need?

SelectViewModel
TextareaViewModel
CheckboxViewModel ?

How about the different types of TextBox like number, datetime etc?

**Comment by thelgevold** [comment]
SelectViewModel
TextareaViewModel
CheckboxViewModel

sounds like a good start. I am thinking we can bind to a type property on TextboxViewModel to render number, email specific textboxes. We can at least start with that for now.
