### ISSUE TITLE
TextBoxViewModel can't extend ViewModelBase<string>

### ISSUE THREAD

**Issue by jpdonaghy** [jpdonaghy/angular-dynamic-forms#4]
TextBoxViewModel can't extend ViewModelBase and hardcode string type and support different types that may have values that are not strings, like Number.

**Comment by thelgevold** [comment]
Agreed.
I am thinking we should add a new model.
```
TextBoxViewModel extends ViewModelBase<number>
```
This would be similar to 
```
CheckboxViewModel extends ViewModelBase<bool>
```

**Comment by jpdonaghy** [comment]
Sounds good.  On it.
