### ISSUE TITLE
Move default value logic to base view model constructor

### ISSUE THREAD

**Issue by thelgevold** [jpdonaghy/angular-dynamic-forms#5]
To avoid duplication between VMs we should move the initialization logic to the base. We could maybe set all of them to 'null'? 

Like this maybe? It's mainly just there to avoid changing the shape of the object.
```
    this.optional = null;
    this.hidden = null;
    this.readOnly = null;
    this.label = null;
    this.value = null;
    this.defaultValue = null;
```

**Comment by jpdonaghy** [comment]
I think all of the properties can be initialized in the base but each VM may have need to also initialize them like value and defaultValue because the type may change between VMs.  The others not so much.

**Comment by jpdonaghy** [comment]
Actually, I'm wrong.  The generic initializes the value and defaultValue so I think all properties can be initializes in the base.  On it.

**Comment by jpdonaghy** [comment]
Or does it, I guess it doesn't.  I stand by my original statement.

**Comment by jpdonaghy** [comment]
Done, only value and defaultValue are left in the VMs.  Added spec for ViewModelBase and removed redundant unit tests.
